### ISSUE TITLE
Changed background menu after 2.5 patcher

### ISSUE THREAD

**Issue by hikarosato** [Eisenmonoxid/S6Patcher#3]
After patching History Edition from Steam, background menu became like it from Gold Edition. Same with base game and addon. But music is correct for both.

![image](https://github.com/user-attachments/assets/45d98b30-508b-4577-9384-bb1b0fd8dc13)

**Comment by Eisenmonoxid** [comment]
Yep, this is intended since i like the Limited Edition background more than the original one (and it looks much better than the background of the Eastern Realm). This change was already introduced in 2.4, see this change:
_- All Versions: The main menu of the game will now show the current S6Patcher version and was slightly reworked._

**Comment by hikarosato** [comment]
Ah then it's not a problem, okay, thank you!
