### ISSUE TITLE
Linux version of the patch?

### ISSUE THREAD

**Issue by Ladripper** [Eisenmonoxid/S6Patcher#4]
Hi, will there ever be a linux version of the patcher? I used it on windows and it worked flawlessly, but have since switched to arch linux and don't know if it's a good idea to use the patcher as-is, considering linux and windows use different filesystems and libraries.
Any chance it'll be worked on in the future?

**Comment by Eisenmonoxid** [comment]
Hey,
Since the original release of Settlers 6 and the history editions are Windows only, i don't think it would make much sense to release a Linux build. I have no plans regarding this right now, i'm sorry.

However, since the functionality of the Patcher is very simple, and it's based on .Net Framework 2.0, you should be able to run it using e.g. [Mono](https://en.wikipedia.org/wiki/Mono_(software)) and it should work fine.

Basically, the latest release of the Patcher modifies a few bytes the game executable and it creates two files in the Documents folder of Settlers 6 (where usermaps are also located). If those changes are made, it worked. I never tried it under Linux, so you would have to try.

If Mono doesn't work, you could also patch your game installation in an windows environment (e.g. by using a virtual machine or another computer) and copy the modified files to your Linux machine.

Regards,
Eisenmonoxid
